### ISSUE TITLE
Feature to create aps patch

### ISSUE THREAD

**Issue by rdutta** [mrdemkin/N64noAAPatcher#1]
Would be nice to have an option to generate an aps patch (i.e. for everdrive auto-patching).

I haven't been able to find a standalone binary that does it (didn't look hard though). There is this js implementation https://github.com/marcrobledo/RomPatcher.js

**Comment by mrdemkin** [comment]
Thanks for request!
I am not familiar with ips/aps, but in theory I understand what is required. Therefore, I will study it and do it. But the primary task is to optimize the speed of work and abandon the use of u64aap and carry out operations with the bytes of the ROM-files with my own algorithms. So I can't promise to add it quickly.
